TRUNCATE TABLE CUST_M;
TRUNCATE TABLE VEN_M;
DELETE FROM EMP WHERE ID<>1;
DELETE FROM USER_D WHERE ID<>1;
DELETE FROM USER_M WHERE ID<>1;
DELETE FROM USER_STORE_D WHERE ID<>1;


TRUNCATE TABLE INVENTORY;
TRUNCATE TABLE PROD_D;
TRUNCATE TABLE PROD_M;
TRUNCATE TABLE RT;
TRUNCATE TABLE RT_D;
TRUNCATE TABLE SO;
TRUNCATE TABLE SO_D;
TRUNCATE TABLE TRANSACTION;
